<template>
  <div class="setting-panel-gui">
    <g-field-collapse
      label="全局"
    >
      <g-field
        :level="2"
        tooltip="请选择您系统有的字体，如果您系统无此字体，标题将会显示默认字体"
        label="字体"
      >
        <g-select
          v-model="config.global.fontFamily"
          :data="fontFamilys"
        />
      </g-field>
      <g-field
        :level="2"
        label="边距"
        :is-flat="true"
      >
        <g-input-number
          v-model="config.global.margin.top"
          :min="-1000"
          :max="1000"
          :step="1"
          is-inline
          label="顶部"
        />
        <g-input-number
          v-model="config.global.margin.bottom"
          :min="-1000"
          :max="1000"
          :step="1"
          is-inline
          label="底部"
        />
        <g-input-number
          v-model="config.global.margin.left"
          :min="-1000"
          :max="1000"
          :step="1"
          is-inline
          label="左侧"
        />
        <g-input-number
          v-model="config.global.margin.right"
          :min="-1000"
          :max="1000"
          :step="1"
          is-inline
          label="右侧"
        />
      </g-field>
      <g-field
        :level="2"
        label="组内间距"
      >
        <g-input-number
          v-model="config.global.innerPadding"
          :min="-1000"
          :max="1000"
          :step="1"
          suffix="px"
        />
      </g-field>
      <g-field
        :level="2"
        label="组间间距"
      >
        <g-input-number
          v-model="config.global.outerPadding"
          :min="-1000"
          :max="1000"
          :step="1"
          suffix="px"
        />
      </g-field>
      <g-field-collapse
        v-model="config.global.background.show"
        :toggle="true"
        label="背景色"
      >
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.global.background.color"
          />
        </g-field>
      </g-field-collapse>
    </g-field-collapse>
    <g-field-collapse
      v-model="config.label.show"
      :toggle="true"
      label="柱子标注"
    >
      <g-field
        :level="2"
        label="位置"
      >
        <g-select
          v-model="config.label.position"
          :data="echartsLablePositions"
        />
      </g-field>
      <g-field
        :level="2"
        label="文本样式"
        :is-flat="true"
      >
        <g-input-number
          v-model="config.label.textStyle.fontSize"
          :min="12"
          :max="100"
          :step="1"
          is-inline
          label="字号"
        />
        <g-color-picker
          v-model="config.label.textStyle.color"
          is-inline
          label="颜色"
        />
        <g-select
          v-model="config.label.textStyle.fontWeight"
          :data="fontWeights"
          is-inline
          label="字体粗细"
        />
      </g-field>
      <g-field
        :level="2"
        label="水平偏移"
      >
        <el-slider
          v-model="config.label.offsetX"
          :min="-1000"
          :max="1000"
          :step="1"
          :show-tooltip="false"
          show-input
          input-size="mini"
          class="g-slider"
        />
      </g-field>
      <g-field
        :level="2"
        label="垂直偏移"
      >
        <el-slider
          v-model="config.label.offsetY"
          :min="-1000"
          :max="1000"
          :step="1"
          :show-tooltip="false"
          show-input
          input-size="mini"
          class="g-slider"
        />
      </g-field>
    </g-field-collapse>
    <g-field-collapse
      v-model="config.xAxis.show"
      :toggle="true"
      label="X轴"
    >
      <g-field-collapse
        v-model="config.xAxis.title.show"
        :toggle="true"
        label="轴标题"
      >
        <g-field
          :level="2"
          label="标题显示"
        >
          <g-input
            v-model="config.xAxis.title.name"
          />
        </g-field>
        <g-field
          :level="2"
          label="位置"
        >
          <g-select
            v-model="config.xAxis.title.location"
            :data="aligns"
          />
        </g-field>
        <g-field
          :level="2"
          label="展示方式"
          :is-flat="true"
        >
          <g-input-number
            v-model="config.xAxis.title.display.rotate"
            :min="0"
            :max="360"
            :step="1"
            is-inline
            label="旋转"
          />
          <g-input-number
            v-model="config.xAxis.title.display.offset"
            :min="-1000"
            :max="1000"
            :step="1"
            is-inline
            label="偏移"
          />
        </g-field>
        <g-field
          :level="2"
          label="文本样式"
          :is-flat="true"
        >
          <g-input-number
            v-model="config.xAxis.title.textStyle.fontSize"
            :min="12"
            :max="100"
            :step="1"
            is-inline
            label="字号"
          />
          <g-color-picker
            v-model="config.xAxis.title.textStyle.color"
            is-inline
            label="颜色"
          />
          <g-select
            v-model="config.xAxis.title.textStyle.fontWeight"
            :data="fontWeights"
            is-inline
            label="字体粗细"
          />
        </g-field>
      </g-field-collapse>
      <g-field-collapse
        v-model="config.xAxis.axisLine.show"
        :toggle="true"
        label="轴线"
      >
        <g-field
          :level="2"
          label="类型"
        >
          <g-select
            v-model="config.xAxis.axisLine.type"
            :data="lineStyles"
          />
        </g-field>
        <g-field
          :level="2"
          label="粗细"
        >
          <g-input-number
            v-model="config.xAxis.axisLine.width"
            :min="0"
            :max="100"
            :step="1"
          />
        </g-field>
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.xAxis.axisLine.color"
          />
        </g-field>
      </g-field-collapse>
      <g-field-collapse
        v-model="config.xAxis.axisTick.show"
        :toggle="true"
        label="轴刻度"
      >
        <g-field
          :level="2"
          label="类型"
        >
          <g-select
            v-model="config.xAxis.axisTick.type"
            :data="lineStyles"
          />
        </g-field>
        <g-field
          :level="2"
          label="粗细"
        >
          <g-input-number
            v-model="config.xAxis.axisTick.width"
            :min="0"
            :max="100"
            :step="1"
          />
        </g-field>
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.xAxis.axisTick.color"
          />
        </g-field>
      </g-field-collapse>
      <g-field-collapse
        v-model="config.xAxis.axisLabel.show"
        :toggle="true"
        label="轴标签"
      >
        <g-field
          :level="2"
          label="两端留白"
        >
          <el-switch
            v-model="config.xAxis.axisLabel.boundaryGap"
          />
        </g-field>
        <g-field
          :level="2"
          label="间隔"
        >
          <g-input
            v-model="config.xAxis.axisLabel.interval"
          />
        </g-field>
        <g-field
          :level="2"
          label="展示方式"
          :is-flat="true"
        >
          <g-input-number
            v-model="config.xAxis.axisLabel.display.rotate"
            :min="0"
            :max="100"
            :step="1"
            is-inline
            label="旋转"
          />
          <g-input-number
            v-model="config.xAxis.axisLabel.display.margin"
            :min="0"
            :max="100"
            :step="1"
            is-inline
            label="偏移"
          />
        </g-field>
        <g-field
          :level="2"
          label="对齐方式"
        >
          <g-select
            v-model="config.xAxis.axisLabel.align"
            :data="hAligns"
          />
        </g-field>
        <g-field
          :level="2"
          label="文本样式"
          :is-flat="true"
        >
          <g-input-number
            v-model="config.xAxis.axisLabel.textStyle.fontSize"
            :min="12"
            :max="100"
            :step="1"
            is-inline
            label="字号"
          />
          <g-color-picker
            v-model="config.xAxis.axisLabel.textStyle.color"
            is-inline
            label="颜色"
          />
          <g-select
            v-model="config.xAxis.axisLabel.textStyle.fontWeight"
            :data="fontWeights"
            is-inline
            label="字体粗细"
          />
        </g-field>
      </g-field-collapse>
      <g-field-collapse
        v-model="config.xAxis.grid.show"
        :toggle="true"
        label="网格线"
      >
        <g-field
          :level="2"
          label="线型样式"
          :is-flat="true"
        >
          <g-select
            v-model="config.xAxis.grid.line.type"
            :data="lineStyles"
            is-inline
            label="类型"
          />
          <g-input-number
            v-model="config.xAxis.grid.line.width"
            :min="0"
            :max="100"
            :step="1"
            is-inline
            label="粗细"
          />
          <g-color-picker
            v-model="config.xAxis.grid.line.color"
            is-inline
            label="颜色"
          />
          <g-input-number
            v-model="config.xAxis.grid.line.dashedLength"
            :min="0"
            :max="100"
            :step="1"
            is-inline
            label="长度"
          />
          <g-input-number
            v-model="config.xAxis.grid.line.dashedSpace"
            :min="0"
            :max="100"
            :step="1"
            is-inline
            label="间距"
          />
        </g-field>
      </g-field-collapse>
    </g-field-collapse>
    <g-field-collapse
      v-model="config.yAxis.show"
      :toggle="true"
      label="Y轴"
    >
      <g-field
        :level="2"
        label="显示范围"
        :is-flat="true"
      >
        <g-input
          v-model="config.yAxis.extent.min"
          is-inline
          label="最小值"
        />
        <g-input
          v-model="config.yAxis.extent.max"
          is-inline
          label="最大值"
        />
      </g-field>
      <g-field-collapse
        v-model="config.yAxis.title.show"
        :toggle="true"
        label="轴标题"
      >
        <g-field
          :level="2"
          label="标题显示"
        >
          <g-input
            v-model="config.yAxis.title.name"
          />
        </g-field>
        <g-field
          :level="2"
          label="位置"
        >
          <g-select
            v-model="config.yAxis.title.location"
            :data="aligns"
          />
        </g-field>
        <g-field
          :level="2"
          label="展示方式"
          :is-flat="true"
        >
          <g-input-number
            v-model="config.yAxis.title.display.rotate"
            :min="0"
            :max="100"
            :step="1"
            is-inline
            label="旋转"
          />
          <g-input-number
            v-model="config.yAxis.title.display.offset"
            :min="0"
            :max="100"
            :step="1"
            is-inline
            label="偏移"
          />
        </g-field>
        <g-field
          :level="2"
          label="文本样式"
          :is-flat="true"
        >
          <g-input-number
            v-model="config.yAxis.title.textStyle.fontSize"
            :min="12"
            :max="100"
            :step="1"
            is-inline
            label="字号"
          />
          <g-color-picker
            v-model="config.yAxis.title.textStyle.color"
            is-inline
            label="颜色"
          />
          <g-select
            v-model="config.yAxis.title.textStyle.fontWeight"
            :data="fontWeights"
            is-inline
            label="字体粗细"
          />
        </g-field>
      </g-field-collapse>
      <g-field-collapse
        v-model="config.yAxis.axisLine.show"
        :toggle="true"
        label="轴线"
      >
        <g-field
          :level="2"
          label="类型"
        >
          <g-select
            v-model="config.yAxis.axisLine.type"
            :data="lineStyles"
          />
        </g-field>
        <g-field
          :level="2"
          label="粗细"
        >
          <g-input-number
            v-model="config.yAxis.axisLine.width"
            :min="0"
            :max="100"
            :step="1"
          />
        </g-field>
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.yAxis.axisLine.color"
          />
        </g-field>
      </g-field-collapse>
      <g-field-collapse
        v-model="config.yAxis.axisTick.show"
        :toggle="true"
        label="轴刻度"
      >
        <g-field
          :level="2"
          label="类型"
        >
          <g-select
            v-model="config.yAxis.axisTick.type"
            :data="lineStyles"
          />
        </g-field>
        <g-field
          :level="2"
          label="粗细"
        >
          <g-input-number
            v-model="config.yAxis.axisTick.width"
            :min="0"
            :max="100"
            :step="1"
          />
        </g-field>
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.yAxis.axisTick.color"
          />
        </g-field>
      </g-field-collapse>
      <g-field-collapse
        v-model="config.yAxis.axisLabel.show"
        :toggle="true"
        label="轴标签"
      >
        <g-field
          :level="2"
          label="两端间距"
        >
          <g-input-number
            v-model="config.yAxis.axisLabel.boundaryGap"
            :min="0"
            :max="100"
            :step="1"
            suffix="%"
          />
        </g-field>
        <g-field
          :level="2"
          label="间隔"
        >
          <g-input
            v-model="config.yAxis.axisLabel.interval"
          />
        </g-field>
        <g-field
          :level="2"
          label="展示方式"
          :is-flat="true"
        >
          <g-input-number
            v-model="config.yAxis.axisLabel.display.rotate"
            :min="0"
            :max="360"
            :step="1"
            is-inline
            label="旋转"
          />
          <g-input-number
            v-model="config.yAxis.axisLabel.display.margin"
            :min="-1000"
            :max="1000"
            :step="1"
            is-inline
            label="偏移"
          />
        </g-field>
        <g-field
          :level="2"
          label="对齐方式"
        >
          <g-select
            v-model="config.yAxis.axisLabel.align"
            :data="hAligns"
          />
        </g-field>
        <g-field
          :level="2"
          label="文本样式"
          :is-flat="true"
        >
          <g-input-number
            v-model="config.yAxis.axisLabel.textStyle.fontSize"
            :min="12"
            :max="100"
            :step="1"
            is-inline
            label="字号"
          />
          <g-color-picker
            v-model="config.yAxis.axisLabel.textStyle.color"
            is-inline
            label="颜色"
          />
          <g-select
            v-model="config.yAxis.axisLabel.textStyle.fontWeight"
            :data="fontWeights"
            is-inline
            label="字体粗细"
          />
        </g-field>
      </g-field-collapse>
      <g-field-collapse
        v-model="config.yAxis.grid.show"
        :toggle="true"
        label="网格线"
      >
        <g-field
          :level="2"
          label="线型样式"
          :is-flat="true"
        >
          <g-select
            v-model="config.yAxis.grid.line.type"
            :data="lineStyles"
            is-inline
            label="类型"
          />
          <g-input-number
            v-model="config.yAxis.grid.line.width"
            :min="0"
            :max="100"
            :step="1"
            is-inline
            label="粗细"
          />
          <g-color-picker
            v-model="config.yAxis.grid.line.color"
            is-inline
            label="颜色"
          />
          <g-input-number
            v-model="config.yAxis.grid.line.dashedLength"
            :min="0"
            :max="100"
            :step="1"
            is-inline
            label="长度"
          />
          <g-input-number
            v-model="config.yAxis.grid.line.dashedSpace"
            :min="0"
            :max="100"
            :step="1"
            is-inline
            label="间距"
          />
        </g-field>
      </g-field-collapse>
    </g-field-collapse>
    <g-field-collapse
      label="系列"
      mode="layout"
      default-layout="horizontal"
      :features="['vertical','horizontal','copy','add','remove']"
      :list="config.series"
      :min="1"
      :max="5"
      :add-item="handleAddSeriesItem"
    >
      <template #default="slotProps">
        <g-field
          :level="2"
          label="系列名称"
        >
          <g-input
            v-model="slotProps.item.name"
          />
        </g-field>
        <g-field-collapse
          label="颜色配置"
        >
          <g-field
            :level="2"
            label="填充类型"
          >
            <el-radio-group
              v-model="slotProps.item.color.type"
            >
              <el-radio-button
                v-for="em in ['solid','gradient']"
                :key="em"
                :label="em"
              >
                {{ em }}
              </el-radio-button>
            </el-radio-group>
          </g-field>
          <g-field
            v-if="slotProps.item.color.type === 'solid'"
            :level="2"
            label="颜色"
          >
            <g-color-picker
              v-model="slotProps.item.color.value"
            />
          </g-field>
          <g-field
            v-if="slotProps.item.color.type === 'gradient'"
            :level="2"
            label="开始颜色"
          >
            <g-color-picker
              v-model="slotProps.item.color.from"
            />
          </g-field>
          <g-field
            v-if="slotProps.item.color.type === 'gradient'"
            :level="2"
            label="结束颜色"
          >
            <g-color-picker
              v-model="slotProps.item.color.to"
            />
          </g-field>
        </g-field-collapse>
      </template>
    </g-field-collapse>
    <g-field-collapse
      v-model="config.animation.enabled"
      :toggle="true"
      label="动画"
    >
      <g-field
        :level="2"
        label="持续时间"
      >
        <g-input-number
          v-model="config.animation.duration"
          :min="0"
          :max="88888888"
          :step="100"
          suffix="ms"
        />
      </g-field>
      <g-field
        :level="2"
        label="缓动效果"
      >
        <g-select
          v-model="config.animation.easing"
          :data="animationEasings"
        />
      </g-field>
      <g-field
        :level="2"
        label="延迟"
      >
        <g-input-number
          v-model="config.animation.delay"
          :min="0"
          :max="88888888"
          :step="100"
          suffix="ms"
        />
      </g-field>
    </g-field-collapse>
  </div>
</template>

<script lang='ts'>
import { defineComponent, PropType, toRef } from 'vue'
import {
  fontFamilys,
  fontWeights,
  hAligns,
  aligns,
  locations,
  lineStyles,
  fillTypes,
  echartsLablePositions,
  animationEasings,
} from '@/data/select-options'
import { BasicBar, BasicBarSeries } from './basic-bar'

export default defineComponent({
  name: 'VBasicBarProp',
  props: {
    com: {
      type: Object as PropType<BasicBar>,
      required: true,
    },
  },
  setup(props) {
    const config = toRef(props.com, 'config')

    const handleAddSeriesItem = () => {
      return new BasicBarSeries(`系列${config.value.series.length + 1}`)
    }

    return {
      config,

      fontFamilys,
      fontWeights,
      lineStyles,
      aligns,
      hAligns,
      locations,
      fillTypes,
      echartsLablePositions,
      animationEasings,
      handleAddSeriesItem,
    }
  },
})
</script>
