<template>
  <div class="setting-panel-gui">
    <g-field-collapse
      label="全局"
    >
      <g-field
        :level="2"
        tooltip="请选择您系统有的字体，如果您系统无此字体，标题将会显示默认字体"
        label="字体"
      >
        <g-select
          v-model="config.global.fontFamily"
          :data="fontFamilys"
        />
      </g-field>
      <g-field
        :level="2"
        label="柱子内间距"
      >
        <el-slider
          v-model="config.global.innerPadding"
          :min="-1000"
          :max="1000"
          :step="1"
          :show-tooltip="false"
          show-input
          input-size="mini"
          class="g-slider"
        />
      </g-field>
      <g-field
        :level="2"
        label="柱子外间距"
      >
        <el-slider
          v-model="config.global.outerPadding"
          :min="-1000"
          :max="1000"
          :step="1"
          :show-tooltip="false"
          show-input
          input-size="mini"
          class="g-slider"
        />
      </g-field>
      <g-field
        :level="2"
        label="背景色"
      >
        <g-color-picker
          v-model="config.global.barColor"
        />
      </g-field>
      <g-field
        :level="2"
        label="边距"
        :is-flat="true"
      >
        <g-input-number
          v-model="config.global.margin.top"
          :min="-88888"
          :max="88888"
          :step="1"
          suffix="px"
          is-inline
          label="顶部"
        />
        <g-input-number
          v-model="config.global.margin.bottom"
          :min="-88888"
          :max="88888"
          :step="1"
          suffix="px"
          is-inline
          label="底部"
        />
        <g-input-number
          v-model="config.global.margin.left"
          :min="-88888"
          :max="88888"
          :step="1"
          suffix="px"
          is-inline
          label="左侧"
        />
        <g-input-number
          v-model="config.global.margin.right"
          :min="-88888"
          :max="88888"
          :step="1"
          suffix="px"
          is-inline
          label="右侧"
        />
      </g-field>
    </g-field-collapse>
    <g-field-collapse
      v-model="config.label.show"
      :toggle="true"
      label="值标签"
    >
      <g-field
        :level="2"
        label="位置"
      >
        <g-select
          v-model="config.label.position"
          :data="echartsLablePositions"
        />
      </g-field>
      <g-field
        :level="2"
        label="文本样式"
        :is-flat="true"
      >
        <g-input-number
          v-model="config.label.textStyle.fontSize"
          :min="10"
          :max="100"
          :step="1"
          suffix="px"
          is-inline
          label="字号"
        />
        <g-color-picker
          v-model="config.label.textStyle.color"
          is-inline
          label="颜色"
        />
        <g-select
          v-model="config.label.textStyle.fontWeight"
          :data="fontWeights"
          is-inline
          label="字体粗细"
        />
      </g-field>
      <g-field
        :level="2"
        label="x方向偏移"
      >
        <el-slider
          v-model="config.label.offsetX"
          :min="-100"
          :max="100"
          :step="1"
          :show-tooltip="false"
          show-input
          input-size="mini"
          class="g-slider"
        />
      </g-field>
      <g-field
        :level="2"
        label="y方向偏移"
      >
        <el-slider
          v-model="config.label.offsetY"
          :min="-100"
          :max="100"
          :step="1"
          :show-tooltip="false"
          show-input
          input-size="mini"
          class="g-slider"
        />
      </g-field>
    </g-field-collapse>
    <g-field-collapse
      v-model="config.xAxis.show"
      :toggle="true"
      label="X轴"
    >
      <g-field-collapse
        label="文本样式"
      >
        <g-field
          :level="2"
          label="字号"
        >
          <g-input-number
            v-model="config.xAxis.textStyle.fontSize"
            :min="12"
            :max="100"
            :step="1"
            suffix="px"
          />
        </g-field>
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.xAxis.textStyle.color"
          />
        </g-field>
        <g-field
          :level="2"
          label="字体粗细"
        >
          <g-select
            v-model="config.xAxis.textStyle.fontWeight"
            :data="fontWeights"
          />
        </g-field>
      </g-field-collapse>
      <g-field-collapse
        label="标签"
      >
        <g-field
          :level="2"
          label="文字距辅助线距离"
        >
          <g-input-number
            v-model="config.xAxis.label.margin"
            :min="-100"
            :max="100"
            :step="1"
            suffix="px"
          />
        </g-field>
      </g-field-collapse>
      <g-field-collapse
        v-model="config.xAxis.axisLine.show"
        :toggle="true"
        label="轴线"
      >
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.xAxis.axisLine.color"
          />
        </g-field>
      </g-field-collapse>
      <g-field-collapse
        v-model="config.xAxis.axisTick.show"
        :toggle="true"
        label="刻度"
      >
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.xAxis.axisTick.color"
          />
        </g-field>
      </g-field-collapse>
    </g-field-collapse>
    <g-field-collapse
      v-model="config.yAxis.show"
      :toggle="true"
      label="Y轴"
    >
      <g-field-collapse
        label="文本样式"
      >
        <g-field
          :level="2"
          label="字号"
        >
          <g-input-number
            v-model="config.yAxis.textStyle.fontSize"
            :min="12"
            :max="100"
            :step="1"
            suffix="px"
          />
        </g-field>
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.yAxis.textStyle.color"
          />
        </g-field>
        <g-field
          :level="2"
          label="字体粗细"
        >
          <g-input
            v-model="config.yAxis.textStyle.fontWeight"
          />
        </g-field>
      </g-field-collapse>
      <g-field-collapse
        label="标签"
      >
        <g-field
          :level="2"
          label="最大值"
        >
          <g-input
            v-model="config.yAxis.label.min"
          />
        </g-field>
        <g-field
          :level="2"
          label="最大值"
        >
          <g-input
            v-model="config.yAxis.label.max"
          />
        </g-field>
        <g-field
          :level="2"
          label="单位"
        >
          <g-input
            v-model="config.yAxis.label.unit"
          />
        </g-field>
        <g-field
          :level="2"
          label="数量"
        >
          <g-input-number
            v-model="config.yAxis.label.amount"
            :min="0"
            :max="88888"
            :step="1"
          />
        </g-field>
        <g-field
          :level="2"
          label="文字距辅助线距离"
        >
          <g-input-number
            v-model="config.yAxis.label.margin"
            :min="-100"
            :max="100"
            :step="1"
            suffix="px"
          />
        </g-field>
      </g-field-collapse>
      <g-field-collapse
        v-model="config.yAxis.axisLine.show"
        :toggle="true"
        label="轴线"
      >
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.yAxis.axisLine.color"
          />
        </g-field>
      </g-field-collapse>
      <g-field-collapse
        v-model="config.yAxis.axisTick.show"
        :toggle="true"
        label="刻度"
      >
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.yAxis.axisTick.color"
          />
        </g-field>
      </g-field-collapse>
    </g-field-collapse>
    <g-field-collapse
      label="系列"
      mode="layout"
      default-layout="horizontal"
      :features="['vertical','horizontal','copy','add','remove']"
      :list="config.series"
      :min="1"
      :max="10"
      :add-item="handleAddSeriesItem"
    >
      <template #default="slotProps">
        <g-field
          :level="2"
          label="系列名称"
        >
          <g-input
            v-model="slotProps.item.name"
          />
        </g-field>
        <g-field-collapse
          label="系列颜色"
        >
          <g-field
            :level="2"
            label="填充类型"
          >
            <el-radio-group
              v-model="slotProps.item.color.type"
            >
              <el-radio-button
                v-for="em in fillTypes"
                :key="em.id"
                :label="em.id"
              >
                {{ em.value }}
              </el-radio-button>
            </el-radio-group>
          </g-field>
          <g-field
            v-if="slotProps.item.color.type === 'solid'"
            :level="2"
            label="颜色"
          >
            <g-color-picker
              v-model="slotProps.item.color.value"
            />
          </g-field>
          <g-field
            v-if="slotProps.item.color.type === 'gradient'"
            :level="2"
            label="开始颜色"
          >
            <g-color-picker
              v-model="slotProps.item.color.from"
            />
          </g-field>
          <g-field
            v-if="slotProps.item.color.type === 'gradient'"
            :level="2"
            label="结束颜色"
          >
            <g-color-picker
              v-model="slotProps.item.color.to"
            />
          </g-field>
        </g-field-collapse>
      </template>
    </g-field-collapse>
    <g-field-collapse
      v-model="config.animation.enabled"
      :toggle="true"
      label="动画"
    >
      <g-field
        :level="2"
        label="持续时间"
      >
        <g-input-number
          v-model="config.animation.duration"
          :min="0"
          :max="888888888"
          :step="1"
          suffix="ms"
        />
      </g-field>
      <g-field
        :level="2"
        label="缓动效果"
      >
        <g-select
          v-model="config.animation.easing"
          :data="animationEasings"
        />
      </g-field>
      <g-field
        :level="2"
        label="延迟"
      >
        <g-input-number
          v-model="config.animation.delay"
          :min="0"
          :max="100"
          :step="1"
          suffix="ms"
        />
      </g-field>
    </g-field-collapse>
  </div>
</template>

<script lang='ts'>
import { defineComponent, PropType, toRef } from 'vue'
import {
  fontFamilys,
  fontWeights,
  fillTypes,
  echartsLablePositions,
  animationEasings,
} from '@/data/select-options'
import { BasicBar, BasicBarSeries } from './basic-bar'

export default defineComponent({
  name: 'VBasicBarProp',
  props: {
    com: {
      type: Object as PropType<BasicBar>,
      required: true,
    },
  },
  setup(props) {
    const config = toRef(props.com, 'config')

    const handleAddSeriesItem = () => {
      return new BasicBarSeries(`系列${config.value.series.length + 1}`)
    }

    return {
      config,

      fontFamilys,
      fontWeights,
      fillTypes,
      echartsLablePositions,
      animationEasings,
      handleAddSeriesItem,
    }
  },
})
</script>
