export { default as GColorPicker } from '../../src/components/ui/color-picker'
export { default as GComIcon } from '../../src/components/ui/com-icon'
export { default as GField } from '../../src/components/ui/field'
export { default as GFieldCollapse } from '../../src/components/ui/field-collapse'
export { default as GInput } from '../../src/components/ui/input'
export { default as GInputNumber } from '../../src/components/ui/input-number'
export { default as GLoading } from '../../src/components/ui/loading'
export { default as GMonacoEditor } from '../../src/components/ui/monaco-editor'
export { default as GSelect } from '../../src/components/ui/select'
export { default as GSelectImage } from '../../src/components/ui/select-image'
export { default as GSelectShape } from '../../src/components/ui/select-shape'
export { default as GSelectSuggest } from '../../src/components/ui/select-suggest'
export { default as GSlider } from '../../src/components/ui/slider'
export { default as GSliderRange } from '../../src/components/ui/slider-range'
export { default as GSwitch } from '../../src/components/ui/switch'
export { default as GTooltipPopover } from '../../src/components/ui/tooltip-popover'
export { default as GUploadImage } from '../../src/components/ui/upload-image'
// -- prepend register placeholder --
