export { default as GColorPicker } from '@/components/ui/color-picker'
export { default as GComIcon } from '@/components/ui/com-icon'
export { default as GField } from '@/components/ui/field'
export { default as GFieldCollapse } from '@/components/ui/field-collapse'
export { default as GInput } from '@/components/ui/input'
export { default as GInputNumber } from '@/components/ui/input-number'
export { default as GLoading } from '@/components/ui/loading'
export { default as GMonacoEditor } from '@/components/ui/monaco-editor'
export { default as GSelect } from '@/components/ui/select'
export { default as GSelectImage } from '@/components/ui/select-image'
export { default as GSelectShape } from '@/components/ui/select-shape'
export { default as GSelectSuggest } from '@/components/ui/select-suggest'
export { default as GSlider } from '@/components/ui/slider'
export { default as GSliderRange } from '@/components/ui/slider-range'
export { default as GSwitch } from '@/components/ui/switch'
export { default as GTooltipPopover } from '@/components/ui/tooltip-popover'
export { default as GUploadImage } from '@/components/ui/upload-image'
// -- prepend register placeholder --
