<template>
  <div class="setting-panel-gui">
    <g-field
      label=""
    >
      <g-input-number
        v-model="config.borderRadius"
        :min="0"
        :max="100"
        :step="1"
      />
    </g-field>
    <g-field-collapse
      label="dfdf"
      mode="layout"
      default-layout="horizontal"
      :features="[]"
      :list="config.fills"
      default-new-value="{}"
    >
      <template #default="slotProps">
        <g-field
          :level="2"
          label=""
        >
          <g-input
            v-model="slotProps.item.fill"
          />
        </g-field>
        <g-field
          :level="2"
          label=""
        >
          <g-input-number
            v-model="slotProps.item.opacity"
            :min="0"
            :max="100"
            :step="1"
          />
        </g-field>
      </template>
    </g-field-collapse>
    <g-field-collapse
      label="vbvb"
    >
      <g-field
        :level="2"
        label=""
      >
        <el-switch
          v-model="config.border.show"
        />
      </g-field>
      <g-field
        :level="2"
        label="cvbcb"
      >
        <el-radio-group
          v-model="config.border.type"
        >
          <el-radio-button
            v-for="em in ['zz','ff','dd']"
            :key="em"
            :label="em"
          >
            {{ em }}
          </el-radio-button>
        </el-radio-group>
      </g-field>
      <g-field-collapse
        v-if="config.border.type === 'zz'"
        label=""
      >
        <g-field
          :level="2"
          label=""
        >
          <g-input-number
            v-model="config.border.flat.width"
            :min="0"
            :max="100"
            :step="1"
          />
        </g-field>
        <g-field
          :level="2"
          label=""
        >
          <g-input
            v-model="config.border.flat.style"
          />
        </g-field>
        <g-field
          :level="2"
          label=""
        >
          <g-input
            v-model="config.border.flat.color"
          />
        </g-field>
      </g-field-collapse>
      <g-field-collapse
        v-if="config.border.type === 'ff'"
        label="sdfdf"
      >
        <g-field
          :level="2"
          label=""
        >
          <g-input-number
            v-model="config.border.linearGradient.width"
            :min="0"
            :max="100"
            :step="1"
          />
        </g-field>
        <g-field-collapse
          label=""
        >
          <g-field
            :level="2"
            label=""
          >
            <g-input-number
              v-model="config.border.linearGradient.color.angle"
              :min="0"
              :max="100"
              :step="1"
            />
          </g-field>
          <g-field-collapse
            label=""
            mode="layout"
            default-layout="horizontal"
            :features="[]"
            :list="config.border.linearGradient.color.stops"
            default-new-value="{}"
          >
            <template #default="slotProps">
              <g-field
                :level="2"
                label=""
              >
                <g-input-number
                  v-model="slotProps.item.offset"
                  :min="0"
                  :max="100"
                  :step="1"
                />
              </g-field>
              <g-field
                :level="2"
                label=""
              >
                <g-input
                  v-model="slotProps.item.color"
                />
              </g-field>
            </template>
          </g-field-collapse>
        </g-field-collapse>
      </g-field-collapse>
      <g-field
        :level="2"
        label=""
      >
        <g-input
          v-model="config.border.imageType"
        />
      </g-field>
      <g-field
        :level="2"
        label=""
      >
        <g-input
          v-model="config.border.presetImage"
        />
      </g-field>
      <g-field-collapse
        label=""
      >
        <g-field
          :level="2"
          label=""
        >
          <g-input
            v-model="config.border.customImage.source"
          />
        </g-field>
        <g-field
          :level="2"
          label=""
        >
          <g-input
            v-model="config.border.customImage.slice"
          />
        </g-field>
        <g-field
          :level="2"
          label=""
        >
          <g-input
            v-model="config.border.customImage.width"
          />
        </g-field>
        <g-field
          :level="2"
          label=""
        >
          <g-input
            v-model="config.border.customImage.outset"
          />
        </g-field>
        <g-field
          :level="2"
          label=""
        >
          <g-input
            v-model="config.border.customImage.repeat"
          />
        </g-field>
      </g-field-collapse>
    </g-field-collapse>
    <g-field-collapse
      label=""
    >
      <g-field
        :level="2"
        label=""
      >
        <g-input
          v-model="config.filter.blur"
        />
      </g-field>
    </g-field-collapse>
    <g-field-collapse
      label=""
    >
      <g-field
        :level="2"
        label=""
      >
        <g-input
          v-model="config.backdropFilter.blur"
        />
      </g-field>
    </g-field-collapse>
    <g-field-collapse
      label=""
    >
      <g-field
        :level="2"
        label=""
      >
        <g-input
          v-model="config.urlConfig.url"
        />
      </g-field>
      <g-field
        :level="2"
        label=""
      >
        <el-switch
          v-model="config.urlConfig.ifBlank"
        />
      </g-field>
    </g-field-collapse>
  </div>
</template>

<script lang='ts'>
import { defineComponent, PropType, toRef } from 'vue'
import {
  fontFamilys,
  fontWeights,
  fontStyles,
  hAligns,
  vAligns,
  writingModes,
  justifyContents,
  aligns,
  angles,
  locations,
  lineStyles,
  fillTypes,
} from '@/data/select-options'
import { BgBox } from './bg-box'

export default defineComponent({
  name: 'VBgBoxProp',
  props: {
    com: {
      type: Object as PropType<BgBox>,
      required: true,
    },
  },
  setup(props) {
    const config = toRef(props.com, 'config')

    return {
      config,

      fontFamilys,
      fontWeights,
      fontStyles,
      hAligns,
      vAligns,
      writingModes,
      justifyContents,
      aligns,
      angles,
      locations,
      lineStyles,
      fillTypes,
    }
  },
})
</script>
